### ISSUE TITLE
Action Plan for Sprint CW 29/30 

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#173]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/93
Next Sprint: 

## Planned Items

- Quick Link for `CW 29/30` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+29%2F30%22)

- Below is a summary of the top level plan items:

**Extension**
- [ ] FEATURE – EXT - Ability to add enhancement specific to VSCode or SAP Business Application Studio #164
- [x] FEATURE - EXT - Accessibility standard - Keyboard navigation ( tab and read order ) #134
- [ ] FEATURE - EXT - Minimum Contrast #135
- [x] FEATURE - EXT - Introduce ability to call GD extension to open a node directly via command #174

**API**
- [ ] FEATURE - API - Add ability to submit general feedback e.g. Is this content helpful on guide answers #97
- [ ] FEATURE - API - Add ability to submit 'solved' and 'not solved' feedback #95
- [ ] FEATURE - API - Add ability to filter the search results based on Software Components #40
- [ ] FEATURE - API - Add ability to filter the search results based on Products #39
