### ISSUE TITLE
FEATURE - Introduce ability to call GD extension to open a node directly via command

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#174]
_As a **developer using an extension such as SAP Fiori tools**,
I want to **see a Guided Answers node directly opened for troubleshooting via command**,
so that I **can see the LINKED guided answer node right away and not navigate through the Guided Answer tree to reach the right node**_

### Description

- Currently, Guided Answers extension can be opened and pass on a `treeID`, but it does not have capability to launch a specific node from that tree. 
- Opening the node directly will help other products to directly call a specific node
- Examples in web application:
https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:45996:45999:50743:51192
Here, tree: 3046
Node can be 45995/45996/45999/50743/51192 

 
### Technical Design
Command to open Guided Answers `sap.ux.guidedAnswer.openGuidedAnswer` allows currently parameter `treeId` to be passed:
https://github.com/SAP/guided-answers-extension/blob/17bf82b61c4844a650473a79a1b89dd514273cba/packages/ide-extension/src/extension.ts#L13 

We should create a new type for `options` in that contains the already existing `treeId` and additionally an optional array of node Ids, that path to the node that is to be displayed. 

```
treeId: number
nodeIdPath?: number[]
```

If an array `nodeIdPath` is passed to the command, it needs to be traversed starting from the `treeId` and validated. While traversing the path, array `guidedAnswerTrees` of the webapp application state has to be filled:
https://github.com/SAP/guided-answers-extension/blob/617f359a64c8083d673de35151ded57fc61486d1/packages/webapp/src/webview/types.ts#L5

As this might be rather slow, because we need to load all nodes along the path one by one, we could ask @JonWiens whether the API could support loading a complete path at once, like it is done in the web implementation.

The caller of command can also pass just one node ID in `nodeIdPath`. In that case the node will be displayed directly.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a product which is calling Guided Answers extension
**when** I am given an option to display a guide to troubleshoot 
**then** I should be shown Guided Answers extension with specific node open

### Tasks
- [ ] Create a new extension enhancement as an example
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by Klaus-Keller** [comment]
Loading a sequence of nodes takes too long, had to implement a loading indicator.
Sneak preview:

![Screen Recording 2022-07-15 at 3 50 42 PM (1)](https://user-images.githubusercontent.com/66327622/179245141-f42642c1-605b-4efe-97e6-48875229b51c.gif)
