### ISSUE TITLE
Action Plan for Sprint CW 31/32

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#182]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/173
Next Sprint: https://github.com/SAP/guided-answers-extension/issues/173

## Planned Items

- Quick Link for `CW 31/32` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+31%2F32%22)

- Below is a summary of the top level plan items:

**Extension**
- [x] FEATURE - EXT - Accessibility standard - Keyboard navigation ( tab and read order ) #134
- [x] FEATURE - EXT - Minimum Contrast #135
- [ ] FEATURE - EXT - Add ability to filter the search results based on Products #39
- [ ] FEATURE - EXT - Add ability to filter the search results based on Software Components #40
- [ ] FEATURE - EXT - Allow users to input whether the guided answer 'solved' or 'not solved' their issue #96

**API**
