### ISSUE TITLE
Action Plan for CW 33/34

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#204]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/173
Next Sprint: https://github.com/SAP/guided-answers-extension/issues/

## Planned Items

- Quick Link for `CW 33/34` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+33%2F34%22)

- Below is a summary of the top level plan items:

**Extension**
- [ ] FEATURE - EXT - Add ability to filter the search results based on Products #39
- [ ] FEATURE - EXT - Add ability to filter the search results based on Software Components #40
- [x] FEATURE - Ext: Show Product and Component info in the List View #199

**API**
