### ISSUE TITLE
Action Plan for 37/38

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#227]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/207

## Planned Items

- Quick Link for `CW 37/38` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+37%2F38%22+)

- Below is a summary of the top level plan items:

**Extension**
- [x] FEATURE - EXT - Add ability to filter the search results based on Products #39
- [x] FEATURE - EXT - Add ability to filter the search results based on Software Components #40 
- [ ] FEATURE - EXT - Allow users to input whether the guided answer 'solved' or 'not solved' their issue #96
- [x] FEATURE - EXT - Connecting Product Filter with the Component Filter and vice versa #230

**API**
-[ ] FEATURE - API - Inputting Node and HTML enhancements via the GA editor #81
