### ISSUE TITLE
Action Plan for CW 39/40

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#241]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/227

## Planned Items

- Quick Link for `CW 39/40` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+39%2F40%22+)

- Below is a summary of the top level plan items:

**Extension**
- [x] TBI - EXT - Consume @sap-ux/ui-components in Guided Answer extension #244
- [x] BUG - EXT - UX Polishing of Filter #248
 - [ ] FEATURE - EXT- Accessibility standard - Keyboard navigation through the Products and Component Filter Popups #240

**API**
-[ ] FEATURE - API - Inputting Node and HTML enhancements via the GA editor #81
