### ISSUE TITLE
Action Plan for CW 41/42

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#246]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/227

## Planned Items

- Quick Link for `CW 39/40` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+39%2F40%22+)

- Below is a summary of the top level plan items:

**Extension**
- [x] FEATURE - EXT - Allow users to input whether the guided answer 'solved' or 'not solved' their issue #96
- [ ] FEATURE - EXT - Allow users to enter general feedback about guide #137
- [x] FEATURE - EXT -  Show list of guides shortlisted for each dev type in SAP Business Application Studio #245
- [x] FEATURE - EXT - Add pagination to the returned search list #270 

**API**
-[ ] FEATURE - API - Inputting Node and HTML enhancements via the GA editor #81
