### ISSUE TITLE
FEATURE - Open/reuse existing Guided answers extension instance 

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#258]
_As a developer using Guided Answers in SBAS or VSCode,
I want Guided Answers to always open 1 instance (whether i reopen GA or GA is opened via other tools),
so that I can reuse the already existing instance and not have multiple tabs open for each new command.

### Description

- Will provide good UX and less opened tabs
- Proposal: Some users might like to open it in different tabs/instances, so provide an extension settings for this behavior. So a user can choose what behavior best suits them.

### Technical Design
@Klaus-Keller to add

### Acceptance Criteria

**Given** I have Guided Answers extension already open
**when** I execute the command `SAP: Open Guided Answers` OR vscode command executed by other tools
**then** the same instance will be reused rather than opening a new instance

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by theStiggySpd** [comment]
@unseen1980  Extension setting name and description:

`Guided Answers: Reuse existing instance`
- [X] If enabled, Guided Answers will open reusing already(if any) existing instance

So, by defualt, GA will reuse already opened instance. If user disables this setting, GA will be open as new tab each time.

@Klaus-Keller @ritarora @carwelsh  Please feel free to suggest any better wording

**Comment by Klaus-Keller** [comment]
@theStiggySpd, fully agree with the technical aspect of it, but I'd try to choose a less technical wording. 

**Proposal**
`Always open Guided Answers in new tab` and default would be false in that case.

**Comment by theStiggySpd** [comment]
> @theStiggySpd, fully agree with the technical aspect of it, but I'd try to choose a less technical wording.
> 
> **Proposal** `Always open Guided Answers in new tab` and default would be false in that case.

Thanks @Klaus-Keller Updated above https://github.com/SAP/guided-answers-extension/issues/258#issuecomment-1377775759

**Comment by Klaus-Keller** [comment]
PR has been merged, closing this ticket.
