### ISSUE TITLE
Action Plan CW 45/46

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#293]
Previous Action Plan: https://github.com/SAP/guided-answers-extension/issues/267
Next Action Plan: https://github.com/SAP/guided-answers-extension/issues/294

- [x] TBI - Consume Guided Answers API V3 #296
- [ ] TBI - EXT - Telemetry set up #122
- [x]  EXT - Allow users to enter general feedback about guide  #137
