### ISSUE TITLE
Action Plan CW 47/48

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#294]
Previous Action Plan: https://github.com/SAP/guided-answers-extension/issues/293
Next Action Plan: https://github.com/SAP/guided-answers-extension/issues/295

- [ ] FEATURE - Introduce opening Guided Answer open to side when called via other extensions #263 
- [ ] FEATURE - Open/reuse existing Guided answers extension instance #258
- [ ] TBI - Investigation into Analyser for smart home page #243
