### ISSUE TITLE
Action Plan CW 49/50

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#295]
**Grooming Topics:**
- [ ] FEATURE - Enhance search results to show relevant node(s) #309
- [ ] FEATURE - Add ability to extract shareable guide info (short link) and ability to quick launch within extension #311
- [ ] FEATURE - Introduce ability to show node enhacements #310

@Klaus-Keller :
- [ ] TBI - EXT - Telemetry set up #122
- [ ] FEATURE - Consume enhancements from GA API #308

@unseen1980 :
- [ ] BUG - General Feedback Message sent pop up still remains when you re visit the tree #306
- [ ] BUG - Search page bugs (November) #299
- [ ] TBI - Switch from enzyme to react testing library #271

Sanat
- [ ] FEATURE - Introduce opening Guided Answer open to side when called via other extensions #263
- [ ] FEATURE - Introduce ability to show node enhacements #310 (Provided we have groomed this good enough by around 7th December)
