### ISSUE TITLE
TBI: Enhance some UX parts for 1st release

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#41]
### Description (include screenshots)
This TBI will add some UX changes in preparation for the first release. Please note this is just for a bit of clean up. Future UX enhancements will be made in separate tickets with involvement and direction from UX colleagues.

Currently, the initial launch view of guided answers extensions looks like this:
![image](https://user-images.githubusercontent.com/59027566/165167751-17732dc6-7520-455e-992a-25f7e3b8f7e6.png)

Please see the tasks below to see list of minor UX enhancements

### Value
- Good first impressions
- Presentable compared to Guided Answers web application

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
Changes in Guided Answers list page/view:
- [x] Add tab title as `Guided Answers extension by SAP` (https://github.com/SAP/guided-answers-extension/pull/50)
- [x] Add `SAP icon` before `Guided Answers` header (done with https://github.com/SAP/guided-answers-extension/pull/30)
- [ ] Add `Interactive documentation designed to help troubleshoot issues, navigate processes and guide through tasks.` after `Guided Answers` header
- [x] Add `Search` title above Search text box
- [ ]  Align all the controls and search results correctly in the Guided answers list page

Changes in Guided answers details view:
- [x] Align and adjust the font size for the `Guided Answers: <name of the branch>`
![image](https://user-images.githubusercontent.com/59027566/165169085-2af2117b-dd33-4f65-b45e-699a001912c7.png) (done with https://github.com/SAP/guided-answers-extension/pull/30)
 
- [x] Remove the buttons which was carried over from POC. This will be added later as a new feature request with instructions in the guided answers reflecting that
![image](https://user-images.githubusercontent.com/59027566/165169393-25b49cf4-fbb1-4c90-be97-c28d69e3e09d.png)

**Comment by carwelsh** [comment]
closing, covered with new designs
