### ISSUE TITLE
TBI - EXT - Telemetry updates 

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#440]
### Description (include screenshots)
To enhance GA UX

### Value
Make  improvements to the Guided Answer UX 

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks 

- [x] Find out the count of nodes open per tree (Group by FIORI TOOLS TREE) / How many nodes are opened in a tree
- [x] What is per product and software component count (should include 3,2,1)
- [x] How many guides a user is opening in a session?
- [x] What was the source of launching GA? Direct command or called from other product? (should include 1 and 2)
- [x] Which filters (product/components) are selected and how often
- [x] How often a user searches for a guide?
- [x] How often the component filter is used? How often product filter is used? How often is the filter used combined?
- [x] I like to know which path (tree -> node ->node) was chosen
- [x] How many results are returned from executing a search / How many guides are shown in the list on opening GA or executing a search?
- [x] How many users clear the filter on opening GA in SBAS
- [x] How many and what commands ( node or HTML enhancements) (action link) being executed using GA
- [x] count of "this solved my issue" vs "this did not solve my issue"
- [x] How many users reached the last node of a tree?
- [x] How many nodes a user clicks into in a tree?
- [x] How many users provide feedback?
- [x] How many users share a link?
- [x] How many users open the web application?

### Acceptance Criteria
- All these items are capture and viewable in the GA Telemetry dashboard.

**Comment by carwelsh** [comment]
@oliversberzs Could you update the excel with the event details.?

**Comment by oliversberzs** [comment]
@carwelsh @ritarora done & merged
