### ISSUE TITLE
[Recurring] TBI - consume latest version of dependencies and transitive dependencies

### ISSUE THREAD

**Issue by hitesh-parmar** [SAP/guided-answers-extension#595]
### Description (include screenshots)

With this TBI we would like to make sure that we constantly update our dependencies and transitive dependencies to their latest versions.

### Value

This helps consume the latest features and security fixes that are included in the modules.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] update @sap-ux/ui-components
- [ ] update @sap/bas-sdk
- [ ] update transitive dependencies
