### ISSUE TITLE
TBI - Enhance UX of Guide Details Page

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#60]
### Description (include screenshots)
This TBI will help to list and develop the UX design of Guide details page. The initial/immediate goal will be to bring the look and feel of guide details page pretty closer to whats there in the Guided Answer web application, with minimal development effort. 

- [ ] Add Home button which takes directly to Guide List Page
- [ ] Add `Start Over` button which remains disabled at root node and becomes active later in the branch. Start Over will take you to root node.
- [ ] Rename `Go Back` to `Go Back one step`
- [ ] Make `Step Navigation panel` collapsible/adaptive
- [ ] Style `Guide Header` section
- [ ] Style `Step Header` section
  

### Value
Improved UX

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by carwelsh** [comment]
closing - covered by the new designs
