### ISSUE TITLE
Action Plan for Sprint CW 25/26

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#88]
Previous Sprint: NA
Next Sprint: https://github.com/SAP/guided-answers-extension/issues/93

## Planned Items

- Quick Link for `CW 25/26` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+25%2F26%22)

- Below is a summary of the top level plan items:

- [x] Enhance Guided Answers Extension Home/List Page #89
- [x] Enhance Guided Answers Extension Content/Details Page #90
- [x]  UX enhancements to Content Tree component in GA content pages #91
- [x] FEATURE - Ability to launch Environment Check by SAP Fiori tools from Guides #144
- [ ] FEATURE - Allow users to input whether the guided answer 'solved' or 'not solved' their issue #96
