### ISSUE TITLE
Action Plan for Sprint CW 27/28

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#93]
Previous Sprint: https://github.com/SAP/guided-answers-extension/issues/88
Next Sprint: https://github.com/SAP/guided-answers-extension/issues/93

## Planned Items

- Quick Link for `CW 29/30` : Github [Issues](https://github.com/SAP/guided-answers-extension/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CW+27%2F28%22)

- Below is a summary of the top level plan items:

- [x] FEATURE - EXT - Give search bar focus on opening of the extension #143
- [x] FEATURE - EXT - Update top buttons #138
- [ ] TBI - EXT - Backfill unit tests for UI Components #141
- [ ] Document: Release and Testing Strategy #106
- [ ] FEATURE - EXT - Allow users to input whether the guided answer 'solved' or 'not solved' their issue #96
